### ISSUE TITLE
Does anyone update peek to work with  201708+ client?

### ISSUE THREAD

**Issue by sctnightcore** [MStr3am/PEEK#6]
`Does anyone update peek to work with the 201708+ client?`

**Comment by 4144** [comment]
Exists one Nemo fork where was fixed some patches for 2017 clients: https://github.com/secretdataz/NEMO
But now it inactive too.

Probably i will create soon another fork with some fixed patches + patches for Zero clients.
But I will update patches only what I need.

**Comment by sctnightcore** [comment]
@4144 
Thanks for answering my question.
I just want the peek to work for 201708+ client.

**Comment by 4144** [comment]
@sctnightcore here is updated version https://gitlab.com/4144/peek
